-- ============================================
-- CUADERNO DE BITÁCORAS - ACTIVITY LOG
-- ============================================
-- Ejecutar en SQL Editor de Supabase

-- 1. Crear tabla de registro de actividades
CREATE TABLE IF NOT EXISTS activity_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  user_email TEXT NOT NULL,
  action_type TEXT NOT NULL CHECK (action_type IN ('check', 'uncheck', 'ignore', 'reactivate')),
  target_table TEXT NOT NULL DEFAULT 'audit_urls',
  target_id BIGINT NOT NULL,
  target_url TEXT,
  issue_type_id BIGINT,
  old_status TEXT,
  new_status TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Índices para consultas rápidas
CREATE INDEX IF NOT EXISTS idx_activity_log_user ON activity_log(user_id);
CREATE INDEX IF NOT EXISTS idx_activity_log_created ON activity_log(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_activity_log_action ON activity_log(action_type);

-- 3. Habilitar RLS
ALTER TABLE activity_log ENABLE ROW LEVEL SECURITY;

-- 4. Políticas: Solo admins pueden ver todos, usuarios pueden ver los suyos
CREATE POLICY "Usuarios pueden ver su propia actividad" 
  ON activity_log FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Usuarios pueden insertar su propia actividad" 
  ON activity_log FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

-- Para SuperAdmin (puedes ajustar el email):
-- CREATE POLICY "SuperAdmin puede ver todo" 
--   ON activity_log FOR SELECT 
--   USING (auth.jwt() ->> 'email' = 'tu-email-superadmin@ejemplo.com');

-- 5. Vista para el dashboard de SuperAdmin
CREATE OR REPLACE VIEW v_activity_dashboard AS
SELECT 
  al.id,
  al.user_email,
  al.action_type,
  al.target_url,
  al.old_status,
  al.new_status,
  it.title AS issue_type_title,
  al.created_at,
  TO_CHAR(al.created_at AT TIME ZONE 'Europe/Madrid', 'DD/MM/YYYY') AS fecha,
  TO_CHAR(al.created_at AT TIME ZONE 'Europe/Madrid', 'HH24:MI:SS') AS hora
FROM activity_log al
LEFT JOIN issue_types it ON al.issue_type_id = it.id
ORDER BY al.created_at DESC;

-- 6. Verificar creación
SELECT 'activity_log table created successfully!' AS status;
