-- ============================================
-- CUADERNO DE BITÁCORAS (Chat System)
-- ============================================

-- 1. Tabla de Mensajes
CREATE TABLE IF NOT EXISTS chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    email TEXT,
    text TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Habilitar RLS
ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;

-- 3. Políticas de Seguridad (Estrictas)

-- Lectura: Todos los autenticados pueden leer
CREATE POLICY "Enable read access for authenticated users" 
ON chat_messages FOR SELECT 
TO authenticated 
USING (true);

-- Escritura: Todos los autenticados pueden escribir
CREATE POLICY "Enable insert access for authenticated users" 
ON chat_messages FOR INSERT 
TO authenticated 
WITH CHECK (auth.uid() = user_id);

-- IMPORTANTE: NO SE CREA POLÍTICA DE DELETE NI UPDATE
-- Esto hace que la tabla sea "Append Only" para los usuarios normales.
-- Ni siquiera el propio autor puede borrar su bitácora.
