-- Create table for chat messages
create table public.chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  email text,
  text text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.chat_messages enable row level security;

-- Create policies
create policy "Anyone can read messages"
  on public.chat_messages for select
  using ( true );

create policy "Authenticated users can insert messages"
  on public.chat_messages for insert
  with check ( auth.role() = 'authenticated' );

-- Enable Realtime
alter publication supabase_realtime add table public.chat_messages;
