// Colección masiva de frases para mantener la moral alta (o al menos la ironía).
const quotes = [
    "Si el SEO fuera fácil, se llamaría 'Poner anuncios'.",
    "Un buen SEO es como el gimnasio: duele, tarda, pero al final te ves bien.",
    "El mejor lugar para esconder un cadáver es la segunda página de Google.",
    "No es un bug, es una 'feature' no documentada de SEO negativo.",
    "Google no te odia, solo ignora tu existencia.",
    "Tu web carga tan lento que Google la indexó por fax.",
    "La paciencia es la madre del SEO, la desesperación es la prima del PPC.",
    "Mis meta-tags tienen más personalidad que mi ex.",
    "Habla con Google, pero que parezca que hablas con el usuario.",
    "Ese enlace roto me duele más a mí que a ti.",
    "Corregir errores 404 es mi terapia zen.",
    "Canonicalízate a ti mismo primero.",
    "Si no está en el index, ¿realmente sucedió?",
    "El sitemap es el mapa del tesoro, pero el tesoro es tráfico orgánico.",
    "H1: La etiqueta que susurra a los algoritmos.",
    "Alt text: Porque Google es ciego pero no tonto.",
    "Link building es hacer amigos, pero con PageRank.",
    "No hagas Black Hat, que Google tiene un sombrero más grande.",
    "El contenido es el rey, pero el contexto es la reina que manda.",
    "Un servidor rápido es un servidor feliz.",
    "Core Web Vitals: La triada del pánico.",
    "LCP: Largest Contentful Pain (en el trasero).",
    "CLS: Cuando tu web baila más que tú en la discoteca.",
    "FID: La primera impresión cuenta, y mucho.",
    "Mobile-first: Porque nadie navega desde una tostadora.",
    "Schema.org: El esperanto de los buscadores.",
    "Rich Snippets: El maquillaje de tu resultado de búsqueda.",
    "Zero click searches: Google robándote el tráfico con estilo.",
    "Voice search: Optimiza para gente que grita a su teléfono.",
    "Local SEO: Para que te encuentre hasta tu vecina.",
    "Google My Business: El LinkedIn de las tiendas de barrio.",
    "Keyword research: Leer la mente colectiva de la humanidad.",
    "Long tail keyword: La cola larga que mueve al perro.",
    "Bounce rate: Cuando entran, ven tu cara y se van.",
    "Dwell time: Quedarse a tomar un café en tu web.",
    "CTR: Click Through Rate, o 'Cuanto Te Reclaman'.",
    "ROI: El rey de las siglas que importan.",
    "KPI: Key Performance Indicator, o 'Ke Pasa Imbécil' si no sube.",
    "Screaming Frog: La mascota oficial de los SEOs técnicos.",
    "Ahrefs: La bola de cristal que cuesta una pasta.",
    "Semrush: La navaja suiza que corta y a veces pincha.",
    "Google Search Console: El confesionario de tus pecados web.",
    "Google Analytics: Dónde ver cómo nadie visita tu blog.",
    "Cookies: Las únicas que nadie quiere comer.",
    "GDPR: El popup que nadie lee y todos aceptan.",
    "HTTPS: El candadito que separa a los profesionales de los amateurs.",
    "SSL: Seguridad Sin Límites (mentira, pero suena bien).",
    "Redirect 301: Mudarse de casa y dejar una nota en la puerta.",
    "Redirect 302: Irse de vacaciones y volver (quizás).",
    "Error 500: El servidor ha colapsado, sálvese quien pueda.",
    "Error 503: Cerrado por reformas, volvemos en 5 minutos.",
    "Robots.txt: El portero de discoteca de tu web.",
    "Noindex: La capa de invisibilidad de Harry Potter.",
    "Nofollow: Te quiero, pero no te paso mi 'juice'.",
    "Disavow tool: El botón de 'negar a la familia tóxica'.",
    "Backlink tóxico: Como un amigo que te pide dinero y no devuelve.",
    "PBN: Private Blog Network, o 'Para Buscar Naufragios'.",
    "Guest blogging: Escribir gratis para que otro gane dinero.",
    "Content pruning: Podar el jardín para que crezcan las flores.",
    "Evergreen content: El contenido que nunca envejece (como Jordi Hurtado).",
    "Clickbait: 'No creerás lo que pasó después con este H2'.",
    "Duplicate content: El gemelo malvado que arruina tu ranking.",
    "Keyword stuffing: Poner palabras clave como si fuera relleno de pavo.",
    "Cloaking: Enseñarle una cosa a Google y otra a tu madre.",
    "Doorway pages: Puertas giratorias que marean al usuario.",
    "Spam score: El numerito que te dice cuán sucio eres.",
    "Domain Authority: La nota del examen que pone una empresa privada.",
    "Page Authority: La nota de cada pregunta del examen.",
    "Trust Flow: ¿Confiarías en esta web para cuidar a tu gato?",
    "Citation Flow: Cuánta gente habla de ti (aunque sea mal).",
    "Anchor text: El texto que oculta el destino final.",
    "Internal linking: La telaraña que trapó a Spider-Man.",
    "Orphan pages: Páginas tristes que nadie quiere enlazar.",
    "Breadcrumbs: Migas de pan para no perderse en el bosque.",
    "Pagination: Divide y vencerás (o aburrirás).",
    "Infinite scroll: El pozo sin fondo de la procrastinación.",
    "Lazy loading: Cargar lento para parecer rápido.",
    "Minify CSS: Ponerlo a dieta para que quepa en el bikini.",
    "Gzip compression: Apretar la maleta para no pagar equipaje extra.",
    "CDN: Content Delivery Network, o 'Corre Dámelo Now'.",
    "Cache: La memoria a corto plazo de tu navegador.",
    "TTFB: Time To First Byte, o 'Tarda Tanto Final Bucle'.",
    "Render-blocking resources: El portero que no deja pasar a nadie.",
    "JavaScript SEO: Enseñar trucos nuevos a un perro viejo (Googlebot).",
    "SPA: Single Page Application, o 'Solo Problemas Añadidos' para SEO.",
    "SSR: Server Side Rendering, o 'Si Si Renderiza'.",
    "CSR: Client Side Rendering, o 'Casi Siempre Rompe'.",
    "Hydration: Darle agua al HTML seco para que viva.",
    "Prerendering: Cocinar antes de que lleguen los invitados.",
    "Dynamic rendering: Menú diferente para humanos y robots.",
    "Log file analysis: Leer el diario íntimo del servidor.",
    "Crawl budget: El dinero que Google quiere gastar en ti (poco).",
    "Index bloat: Estar gordo de páginas inútiles.",
    "Thin content: Contenido anoréxico que necesita un bocadillo.",
    "Keyword cannibalization: Tus páginas comiéndose entre ellas.",
    "SERP: Search Engine Results Page, el campo de batalla.",
    "Featured Snippet: La posición cero, el trono de hierro.",
    "Knowledge Graph: El cerebro gigante que todo lo sabe.",
    "Google Discover: El feed que te da tráfico cuando quiere.",
    "Google News: Noticias frescas para gente con prisa.",
    "Algorithm update: El terremoto que tira tu casa abajo.",
    "Panda: El oso que odia el contenido basura.",
    "Penguin: El pingüino que congela los enlaces malos.",
    "Hummingbird: El colibrí que entiende lo que dices, no lo que escribes.",
    "RankBrain: La IA que dominará el mundo (del SEO).",
    "BERT: El primo listo de la IA que lee contexto.",
    "MUM: Multitask Unified Model, la madre de todas las IAs.",
    "E-E-A-T: Experience, Expertise, Authoritativeness, Trustworthiness (y Tacos).",
    "YMYL: Your Money Your Life, o 'Ya Me Yodes La vida'.",
    "Sandbox: El parque de juegos donde Google te castiga.",
    "Honeymoon period: Cuando Google te ama al principio y luego te ignora.",
    "SEO Audit: La autopsia de una web viva.",
    "SEO Strategy: El plan para dominar el mundo (o un nicho).",
    "Competitor analysis: Espiar al vecino con prismáticos.",
    "Gap analysis: Ver qué tiene el vecino que no tengas tú.",
    "Content calendar: Promesas de escribir que nunca cumples.",
    "Copywriting: Escribir para vender, no para aburrir.",
    "UX/UI: Que sea bonito y fácil, no un laberinto.",
    "A/B Testing: Probar si el botón rojo vende más que el azul.",
    "Heatmaps: Ver dónde la gente hace clic (spoiler: no es donde quieres).",
    "Conversion Rate Optimization (CRO): Exprimir el limón hasta la última gota.",
    "Lead generation: Buscar agujas en un pajar.",
    "Funnel: El embudo por donde caen los usuarios (y se escapan).",
    "Landing page: La pista de aterrizaje donde se estrellan o vuelan.",
    "Call To Action (CTA): '¡Cómprame ya, por favor!'.",
    "Above the fold: Lo que se ve sin tocar nada.",
    "Below the fold: El sótano oscuro de tu web.",
    "Responsive design: Si no se ve en móvil, no existe.",
    "Hamburger menu: Tres rayas que esconden todo.",
    "Favicon: El iconito que nadie ve pero todos ponen.",
    "404 page: La oportunidad de ser gracioso cuando fallas.",
    "Thank you page: 'Gracias por tu dinero, vuelve pronto'.",
    "User intent: ¿Qué narices quería encontrar este tío?",
    "Informational intent: 'Cómo arreglar lavadora'.",
    "Navigational intent: 'Facebook login'.",
    "Transactional intent: 'Comprar zapatillas baratas'.",
    "Commercial investigation: 'Mejores móviles 2026'.",
    "Brand awareness: Que suenes más que la Coca-Cola.",
    "Social signals: Likes y shares que (dicen que) no cuentan.",
    "Engagement: Que te quieran, o al menos te hablen.",
    "Community management: Lidiar con trolls sin perder la cordura.",
    "Influencer marketing: Pagar a gente guapa para que diga que eres guay.",
    "Email marketing: SPAM con cariño.",
    "Newsletter: El periódico que nadie pidió pero te llega.",
    "Automation: Robots haciendo tu trabajo (mal).",
    "Zapier: El pegamento de internet.",
    "API: El enchufe universal.",
    "Webhook: Cuando pasa algo, avísame.",
    "Scraping: Robar datos legalmente (más o menos).",
    "Python para SEO: Sentirse hacker automatizando un Excel.",
    "Regex: Jeroglíficos para filtrar datos.",
    "Excel: La herramienta SEO más potente (y odiada).",
    "Google Sheets: Excel pero en la nube y lento.",
    "Data Studio (Looker): Gráficos bonitos para clientes que no leen.",
    "Reporting: Inventar excusas de por qué bajó el tráfico.",
    "Client meeting: '¿Por qué no salgo primero por 'hotel'?'.",
    "Freelance life: Trabajar en pijama y cobrar tarde.",
    "Agency life: Café, estrés y ping-pong.",
    "In-house SEO: Luchar contra IT y Marketing a la vez.",
    "Senior SEO: 'Depende'.",
    "Junior SEO: '¡He encontrado un truco infalible!'.",
    "SEO Guru: Vende humos en LinkedIn.",
    "Webinar: Una hora de venta encubierta.",
    "Case study: 'Cómo gané un millón (mintiendo)'.",
    "White paper: Un PDF aburrido para parecer listo.",
    "Podcast: Gente hablando de SEO mientras pasea al perro.",
    "SEO News: Cada día Google cambia algo, pánico diario.",
    "John Mueller: El oráculo que habla con acertijos.",
    "Matt Cutts: El profeta olvidado.",
    "Search Engine Land: La biblia de las noticias SEO.",
    "Search Engine Journal: El otro testamento.",
    "Moz: El abuelo cebolleta del SEO.",
    "Black Friday: El día que tu servidor muere.",
    "Cyber Monday: La resaca del Black Friday.",
    "Navidad: Cuando el CPC se dispara.",
    "Verano: Cuando el tráfico se va a la playa.",
    "Q4: El trimestre del pánico y la gloria.",
    "Budget: Lo que nunca es suficiente.",
    "Deadline: La fecha que se pasa volando.",
    "Scope creep: El proyecto que engorda sin control.",
    "Imposter syndrome: 'No sé nada, Google lo cambia todo'.",
    "Burnout: Cuando sueñas con canonicals.",
    "Digital Nomad: Trabajar desde Bali con wifi de mierda.",
    "Remote work: Trabajar desde casa con el gato en el teclado.",
    "Networking: Beber cerveza con otros frikis.",
    "Conference: Viajar para beber cerveza con otros frikis.",
    "Mastermind: Grupo de terapia para emprendedores.",
    "Niche site: La web de 'mejores afeitadoras de espalda'.",
    "Affiliate marketing: Ganar centimos mientras duermes.",
    "Amazon Associates: Jeff Bezos dándote migajas.",
    "AdSense: Google dándote céntimos.",
    "Display ads: Banners que nadie clica.",
    "Programmatic advertising: Robots comprando a robots.",
    "Native advertising: Publicidad disfrazada de noticia.",
    "Sponsored post: 'Este artículo es genial (me han pagado)'.",
    "Advertorial: Anuncio largo y aburrido.",
    "PR: Public Relations, o salir en el periódico.",
    "HARO: Help A Reporter Out, o mendigar enlaces.",
    "Digital PR: PR pero con enlaces dofollow.",
    "Brand mention: Que hablen de ti (sin enlace, malditos).",
    "Unlinked mention: La oportunidad perdida.",
    "Link reclamation: '¡Eh, ese enlace está roto, pon el mío!'.",
    "Broken link building: 'Tu web está rota, yo te la arreglo (con mi link)'.",
    "Skyscraper technique: Hacerlo más grande y mejor (y robar enlaces).",
    "Ego bait: 'Eres genial, compárteme'.",
    "Infographic: Dibujitos para conseguir enlaces.",
    "Video SEO: YouTube es el segundo buscador, no lo olvides.",
    "YouTube tags: Keywords para vídeos.",
    "Thumbnail: La cara de sorpresa vende.",
    "Closed captions: Para que te lean sin sonido.",
    "Podcast SEO: Transcribe o muere.",
    "Image SEO: Alt, title, nombre de archivo, peso... qué pereza.",
    "WebP: El formato que le gusta a Google.",
    "Lazy load images: Que esperen, que no hay prisa.",
    "CDN for images: Fotos viajeras.",
    "International SEO: Hreflang es el infierno en la tierra.",
    "Hreflang: La etiqueta que siempre rompes.",
    "ccTLD: .es, .fr, .de... colecciona todos.",
    "Subdomain vs Subfolder: La eterna discusión sin fin.",
    "Geo-targeting: Apuntar y disparar.",
    "Translation: No uses Google Translate, por favor.",
    "Localization: Adaptar, no solo traducir.",
    "Migration: El momento de mayor riesgo cardíaco.",
    "Redesign: Cambiarlo todo para que baje el tráfico.",
    "Rebranding: Nuevo logo, mismos problemas.",
    "CMS: WordPress, Shopify, Magento... elige tu veneno.",
    "WordPress: El rey del plugin inflado.",
    "Shopify: Fácil pero caro.",
    "Magento: Potente pero necesitas un ingeniero de la NASA.",
    "Wix: Mejoró, pero los SEOs lo miran mal.",
    "Squarespace: Bonito, pero cerrado.",
    "Custom CMS: 'Lo hacemos a medida', el error fatal.",
    "Plugin: La solución a todo y la causa de todo error.",
    "Yoast SEO: El semáforo que obsesiona a los clientes.",
    "Rank Math: El nuevo chico guapo del barrio.",
    "All in One SEO: El clásico que resiste.",
    "Elementor: Maquetador que mete código basura.",
    "Divi: Otro maquetador pesado.",
    "Gutenberg: El editor de bloques que nadie pidió.",
    "Headless CMS: Para los modernos que usan React.",
    "Next.js: Lo que usa Caldea ahora (¡bien hecho!).",
    "React: JavaScript por todas partes.",
    "Vue.js: El primo indie de React.",
    "Angular: El gigante de Google que nadie usa para SEO.",
    "Node.js: JavaScript en el servidor, locura.",
    "Jamstack: Webs estáticas rápidas como el rayo.",
    "Netlify: Donde viven las webs modernas.",
    "Vercel: La casa de Next.js.",
    "GitHub: Donde guardas tu código (y tus vergüenzas).",
    "Git: Control de versiones para cuando la cagas.",
    "Commit: 'Arreglado bug final final v2'.",
    "Push: Enviar cambios y rezar.",
    "Pull request: 'Por favor, acepta mi código basura'.",
    "Merge conflict: Cuando dos personas tocan lo mismo.",
    "Branch: Una realidad paralela de tu código.",
    "Staging: El ensayo general antes del estreno.",
    "Production: El escenario real donde todo falla.",
    "Deployment: El lanzamiento del cohete.",
    "Rollback: ¡Abortar misión, abortar!",
    "CI/CD: Automatizar el sufrimiento.",
    "Docker: En mi máquina funcionaba.",
    "Kubernetes: Orquestar contenedores (y dolores de cabeza).",
    "AWS: La nube de Amazon que te cobra por respirar.",
    "Google Cloud: La nube de Google.",
    "Azure: La nube de Microsoft.",
    "Serverless: No hay servidor (mentira, es de otro).",
    "Edge function: Código corriendo en el borde del mundo.",
    "Database: Donde viven los datos.",
    "SQL: Hablar con la base de datos.",
    "NoSQL: Base de datos rebelde.",
    "Supabase: 'The open source Firebase alternative'.",
    "Firebase: Google te da backend gratis (hasta que creces).",
    "MySQL: El clásico confiable.",
    "PostgreSQL: El elefante potente.",
    "MongoDB: Documentos JSON voladores.",
    "Redis: Memoria rápida para caché.",
    "API REST: La forma estándar de hablar.",
    "GraphQL: Pide solo lo que necesitas.",
    "JSON: El lenguaje de intercambio universal.",
    "XML: El abuelo verboso del JSON.",
    "AJAX: Cargar cosas sin recargar.",
    "DOM: El árbol de la web.",
    "Virtual DOM: El fantasma del árbol.",
    "Shadow DOM: El lado oscuro del árbol.",
    "Web Components: Piezas de lego para la web.",
    "PWA: Web que se cree app.",
    "Service Worker: El trabajador en la sombra.",
    "Manifest.json: La identidad de tu PWA.",
    "Push notifications: Molestar al usuario en su móvil.",
    "Offline mode: Funcionar sin internet (magia).",
    "App Store Optimization (ASO): SEO para apps.",
    "Google Play Console: Donde subes tu app Android.",
    "App Store Connect: Donde Apple rechaza tu app.",
    "Review mining: Leer reseñas para robar keywords.",
    "Installs: Descargas, el KPI de las apps.",
    "Retention: Que no desinstalen tu app.",
    "Churn: Usuarios que se van para siempre.",
    "LTV: Lifetime Value, cuánto vale un usuario.",
    "CAC: Cost Acquisition Customer, cuánto cuesta pescarlo.",
    "Startup: Empresa sin dinero pero con sueños.",
    "Unicornio: Startup que vale mil millones (y pierde dinero).",
    "Venture Capital: Gente que apuesta dinero en startups.",
    "Angel Investor: Rico que te da dinero.",
    "Bootstrapping: Empezar sin un duro.",
    "MVP: Mínimo Producto Viable (o Mierda Viable Producida).",
    "Pivot: 'Nuestra idea no funciona, cambiemos todo'.",
    "Agile: Moverse rápido y romper cosas.",
    "Scrum: Reuniones diarias para decir que vas retrasado.",
    "Kanban: Post-its en una pizarra.",
    "Sprint: Correr dos semanas para no llegar.",
    "Backlog: La lista de cosas que nunca harás.",
    "User Story: 'Como usuario quiero...'.",
    "Bug report: 'No funciona'.",
    "Feature request: 'Quiero que haga café'.",
    "Documentation: Lo que nadie escribe y nadie lee.",
    "Stack Overflow: Donde copias y pegas código.",
    "ChatGPT: Quien escribe tu código ahora.",
    "Copilot: Tu copiloto que a veces se duerme.",
    "Gemini: La IA de Google que intenta ayudar.",
    "Prompt Engineering: Saber pedirle cosas a la IA.",
    "El cliente siempre tiene la razón (excepto en Keywords).",
    "Mi vida es un constante F5 en Search Console.",
    "SEO no es magia, es ingeniería inversa con ansiedad.",
    "Link Building: El arte de pedir favores sin parecer desesperado.",
    "Si no está en la primera página, es Deep Web.",
    "Google Ads: Pagar por lo que el SEO debería darte gratis.",
    "CPC: Cada Penique Cuenta.",
    "CPM: Coste Por Mil infartos.",
    "CTR bajo: Tu anuncio es más aburrido que un lunes.",
    "Quality Score: Google juzgando tu vida.",
    "Remarketing: Perseguir a tu ex por todo internet.",
    "Pixel de Facebook: El espía que todos aceptamos.",
    "Lookalike aience: 'Busca gente igual de rara que yo'.",
    "Dark Mode: Para SEOs vampiros.",
    "Lorem Ipsum: El texto más leído de internet.",
    "CMS: Causa Muchos Sufrimientos.",
    "FTP: File Transfer Panic.",
    "SSH: Pantalla negra, me siento hacker.",
    "DNS: Donde nacen los problemas de 'no carga'.",
    "Domain expired: El infarto anual.",
    "Two-Factor Authentication: Buscar el móvil desesperadamente.",
    "Password Manager: Olvidar una contraseña maestra para olvidarlas todas.",
    "Phishing: 'Hola, soy un príncipe nigeriano'.",
    "Ransomware: Paga o tus fotos de gatos desaparecen.",
    "VPN: Ver Netflix de otro país.",
    "Incognito Mode: Para buscar vuelos... y 'cosas'.",
    "Cache clear: La solución al 90% de los problemas.",
    "Reboot: La solución al otro 10%.",
    "Ticket de soporte: Botella al mar.",
    "Meeting de viernes tarde: Crimen de lesa humanidad.",
    "Brainstorming: Lluvia de ideas, sequía de resultados.",
    "Briefing: El documento que el cliente no leyó.",
    "Deadline ayer: Clásico.",
    "ASAP: As Soon As Panic.",
    "FYI: For Your Ignorance.",
    "KPIs en rojo: Houston, tenemos un problema.",
    "QBR: Quarterly Business Regret.",
    "Churn rate: La dieta del cliente.",
    "Retention: Abrazar al cliente hasta que pague.",
    "Upselling: '¿Quiere patatas con su SEO?'.",
    "Cross-selling: '¿Y un refresco de Redes Sociales?'.",
    "Brand Ambassador: Fanboy con sueldo.",
    "Community Manager: Psicólogo de masas.",
    "Crisis de reputación: Cuando el becario tuitea.",
    "Viral: Suerte disfrazada de estrategia.",
    "Meme marketing: Usar gatos para vender B2B.",
    "Hashtag: La almohadilla que nadie usa bien.",
    "Trending Topic: Ser famoso 15 minutos.",
    "Storytelling: Contar cuentos para vender motos.",
    "Copywriter: Poeta de ventas.",
    "CTA: Botón rojo grande.",
    "Above the fold: Lo único que importa.",
    "Heatmap: El mapa de calor de tu fracaso.",
    "Scroll depth: Hasta dónde llega el aburrimiento.",
    "Session duration: Cuánto aguantan tu chapa.",
    "Unique visitor: Tu madre entrando desde otro móvil.",
    "Pageview: F5, F5, F5.",
    "Referral traffic: Gracias, tía abuela.",
    "Direct traffic: gente que sabe escribir.",
    "Organic traffic: El santo grial.",
    "Paid traffic: Dopaje legal.",
    "Social traffic: Ruido.",
    "Email traffic: Los fieles.",
    "UTM parameters: La matrícula de tu enlace.",
    "URL shortener: Esconder el monstruo.",
    "QR code: El regreso de los 90.",
    "NFC: Tocar cosas con el móvil.",
    "Beacon: El faro que te espía en la tienda.",
    "Geofencing: Vallar al cliente.",
    "Push notification: '¡Mírame! ¡Mírame!'.",
    "SMS marketing: Que parezca urgente.",
    "Whatsapp Business: Spam en tu bolsillo.",
    "Chatbot: 'No he entendido tu pregunta'.",
    "IA generativa: Escribir sin escribir.",
    "Deepfake: Creer lo que no ves.",
    "Metaverso: El futuro que nadie quiere.",
    "Web3: Cripto y confusión.",
    "NFT: JPEGs caros.",
    "Blockchain: La base de datos lenta.",
    "Smart Contract: Abogado robot.",
    "DeFi: Finanzas sin banco (y sin seguridad).",
    "DAO: Anarquía organizada.",
    "Tokenomics: Economía de monopoly.",
    "Whitepaper: PDF que promete la luna.",
    "Roadmap: Lista de deseos.",
    "Airdrop: Dinero gratis (si tienes suerte).",
    "HODL: Aguantar hasta el suelo.",
    "FOMO: Fear Of Missing Out (Miedo a perderse algo).",
    "FUD: Fear, Uncertainty, Doubt.",
    "Whale: El que mueve el mercado.",
    "Bear market: Todo baja.",
    "Bull market: Todo sube.",
    "Dip: La bajada antes de la subida (o de la quiebra).",
    "Moon: A donde vamos (o no).",
    "Lambo: El coche que nunca tendrás.",
    "WAGMI: We Are All Gonna Make It (mentira).",
    "NGMI: Not Gonna Make It.",
    "DYOR: Do Your Own Research (búscate la vida).",
    "Shill: Vender humo.",
    "Rug pull: Tirar de la alfombra.",
    "Scam: La estafa de cada día.",
    "Vaporware: Software que es humo.",
    "Beta tester: Cobaya humana.",
    "Early adopter: El primero en sufrir los bugs.",
    "Late majority: Tu padre usando TikTok.",
    "Laggard: Tu abuelo con fax.",
    "Disruptive: Romper cosas y llamarlo innovación.",
    "Scalable: Crecer sin explotar.",
    "Synergy: Palabra vacía de reunión.",
    "Holistic: Palabra vacía de marketing.",
    "Leverage: Apalancar (usar el dinero de otro).",
    "Bandwidth: 'No tengo tiempo'.",
    "Deep dive: Mirar algo 5 minutos más.",
    "Low hanging fruit: Lo fácil.",
    "Touchpoint: Tocar al cliente (metafóricamente).",
    "Customer journey: El viaje del héroe (comprador).",
    "Persona: Amigo imaginario al que vendes.",
    "Pain point: Donde le duele.",
    "Value proposition: Por qué tú y no el otro.",
    "USP: Unique Selling Proposition.",
    "B2B: Boring to Boring.",
    "B2C: Business to Consumer.",
    "D2C: Direct to Consumer.",
    "SaaS: Software as a Service (Alquiler eterno).",
    "PaaS: Platform as a Service.",
    "IaaS: Infrastructure as a Service.",
    "XaaS: Anything as a Service.",
    "Monthly Recurring Revenue (MRR): La droga del SaaS.",
    "Annual Recurring Revenue (ARR): La droga anual.",
    "Freemium: Gratis hasta que te gusta.",
    "Trial: La dosis de prueba.",
    "Paywall: El muro de pago.",
    "Subscription fatigue: 'Otrra suscripción no'.",
    "Ad blocker: El enemigo.",
    "Cookie consent: El clic más ignorado.",
    "Data privacy: El oxímoron.",
    "Big Data: Tener muchos datos y no saber qué hacer.",
    "Machine Learning: Estadísticas con esteroides.",
    "Neutral Network: Cerebro digital.",
    "Algorithm: La caja negra.",
    "Black box: Nadie sabe cómo funciona.",
    "Open source: Código comunista.",
    "Proprietary: Código capitalista.",
    "Vendor lock-in: Casado con el proveedor.",
    "Legacy system: El código sagrado que nadie toca.",
    "Technical debt: Intereses de la tarjeta de crédito del código.",
    "Refactoring: Limpiar la casa.",
    "Deprecado: Viejo y obsoleto.",
    "Sunset: Muerte dulce de un producto.",
    "End of Life (EOL): Muerte oficial.",
    "Patch: Tirita digital.",
    "Update: Ruleta rusa.",
    "Hotfix: Parche en caliente (quemando).",
    "Rollout: Despliegue progresivo.",
    "Canary release: Usar a pocos usuarios de cobayas.",
    "Blue-Green deployment: Dos servidores, un destino.",
    "Load balancer: El policía de tráfico.",
    "Microservices: Pequeños problemas distribuidos.",
    "Monolith: Un gran problema sólido.",
    "Container: Caja virtual.",
    "Orchestration: Dirigir la orquesta de cajas.",
    "Virtualization: Matrix para ordenadores.",
    "Cloud computing: El ordenador de otro.",
    "Hybrid cloud: Un pie aquí y otro allá.",
    "Private cloud: Tu propia nube (servidor).",
    "Public cloud: La nube de todos.",
    "Multi-cloud: Complicarse la vida x3.",
    "Edge computing: Computar en el borde.",
    "Fog computing: Computar en la niebla (marketing).",
    "Quantum computing: El futuro que romperá tu cifrado.",
    "IoT: Internet of Things (Tostadoras espía).",
    "Smart home: Casa que se cuelga.",
    "Wearable: Reloj que te manda correr.",
    "VR: Virtual Reality (Mareo digital).",
    "AR: Augmented Reality (Pokémon GO).",
    "MR: Mixed Reality (Gafas caras).",
    "XR: Extended Reality (Todo junto).",
    "5G: Internet rápido (y conspiraciones).",
    "6G: Aún más rápido (ya vendrá).",
    "Starlink: Internet del espacio.",
    "Fiber optic: Luz portadora de memes.",
    "WiFi 6: WiFi mejorado.",
    "Bluetooth: Emparejar es sufrir.",
    "USB-C: El cable único (ojalá).",
    "Thunderbolt: El rayo caro.",
    "HDMI: Audio y vídeo.",
    "DisplayPort: El rival del HDMI.",
    "VGA: El abuelo azul.",
    "DVI: El otro abuelo.",
    "Ethernet: El cable que nunca falla.",
    "Router: La caja parpadeante.",
    "Modem: El traductor de internet.",
    "Switch: El ladrón de enchufes de red.",
    "Firewall: El muro de fuego.",
    "Antivirus: El policía del PC.",
    "Malware: Software malo.",
    "Spyware: Software espía.",
    "Trojan: Caballo de Troya.",
    "Worm: Gusano digital.",
    "Virus: Gripe digital.",
    "Botnet: Ejército zombi.",
    "DDoS: Ataque de denegación de servicio.",
    "SQL Injection: Inyectar código en la base.",
    "XSS: Cross Site Scripting.",
    "Zero-day: Agujero nuevo.",
    "Exploit: Aprovechar el agujero.",
    "Patch Tuesday: Martes de parches.",
    "Hacker: Sombrero blanco, gris o negro.",
    "Cracker: Rompe cosas.",
    "Script kiddie: Niño con scripts.",
    "Hacktivist: Hacker con causa.",
    "Cybersecurity: Seguridad cibernética.",
    "InfoSec: Seguridad de la información.",
    "DevSecOps: Desarrollo, Seguridad y Operaciones.",
    "Pentesting: Probar si entras.",
    "Digital Forensic: CSI digital.",
    "Encryption: Cifrado.",
    "Decryption: Descifrado.",
    "Hash: Huella digital.",
    "Salt: Sal para el hash.",
    "Key: Llave.",
    "Certificate: Carnet de identidad web.",
    "Authority: Quien emite el carnet.",
    "Trust: Confianza.",
    "Identity: Quién eres.",
    "Access Control: Quién entra.",
    "Authentication: Demuestra quién eres.",
    "Authorization: Qué puedes hacer.",
    "Accounting: Qué hiciste.",
    "Audit: Revisar qué hiciste.",
    "Compliance: Cumplir las normas.",
    "Regulation: Las normas.",
    "Standard: Lo normal.",
    "Best practice: Lo mejor.",
    "Protocol: Reglas de comunicación.",
    "Layer: Capa.",
    "Stack: Pila de tecnologías.",
    "Full Stack: Saber de todo (un poco).",
    "Frontend: Lo que se ve.",
    "Backend: Lo que no se ve.",
    "Database Administrator (DBA): Guardián de los datos.",
    "SysAdmin: Dios del servidor.",
    "Network Admin: Dios de la red.",
    "Helpdesk: '¿Ha probado a apagar y encender?'.",
    "CTO: Chief Technology Officer.",
    "CIO: Chief Information Officer.",
    "CISO: Chief Information Security Officer.",
    "CDO: Chief Data Officer.",
    "CEO: Chief Executive Officer.",
    "CFO: Chief Financial Officer.",
    "COO: Chief Operating Officer.",
    "CMO: Chief Marketing Officer.",
];

// Función mágica para obtener frase basada en la hora (determinista)
export function getHourlyQuote() {
    const now = new Date();
    // Usamos la hora y el día para variar, pero mantener consistencia durante la hora
    const seed = now.getHours() + (now.getDate() * 24) + (now.getMonth() * 744);
    const index = seed % quotes.length;
    return quotes[index];
}

export function getRandomQuote() {
    return quotes[Math.floor(Math.random() * quotes.length)];
}


export const historicalQuotes = [
    { text: "Lo imposible es el fantasma de los timoratos y el refugio de los cobardes.", author: "Napoleón Bonaparte" },
    { text: "El éxito no es el final, el fracaso no es fatal: es el coraje para continuar lo que cuenta.", author: "Winston Churchill" },
    { text: "Veni, vidi, vici.", author: "Julio César" },
    { text: "La fortuna favorece a los audaces.", author: "Virgilio" },
    { text: "No he fallado. He encontrado 10.000 formas que no funcionan.", author: "Thomas Edison" },
    { text: "Siempre parece imposible hasta que se hace.", author: "Nelson Mandela" },
    { text: "Un viaje de mil millas comienza con un solo paso.", author: "Lao-Tse" },
    { text: "La mejor manera de predecir el futuro es crearlo.", author: "Peter Drucker" },
    { text: "Si atraviesas el infierno, sigue caminando.", author: "Winston Churchill" },
    { text: "La victoria pertenece al más perseverante.", author: "Napoleón Bonaparte" },
    { text: "Cree que puedes y ya estarás a medio camino.", author: "Theodore Roosevelt" },
    { text: "No cuentes los días, haz que los días cuenten.", author: "Muhammad Ali" },
    { text: "La única forma de hacer un gran trabajo es amar lo que haces.", author: "Steve Jobs" },
    { text: "Estar preparado es la mitad de la victoria.", author: "Miguel de Cervantes" },
    { text: "A menudo el cambio de uno mismo es más necesario que el cambio de escenario.", author: "Séneca" },
    { text: "El hombre que mueve una montaña empieza apartando piedras pequeñas.", author: "Confucio" },
    { text: "La suerte es lo que sucede cuando la preparación se encuentra con la oportunidad.", author: "Séneca" },
    { text: "Haz lo que puedas, con lo que tengas, donde estés.", author: "Theodore Roosevelt" },
    { text: "No busques errores, busca remedios.", author: "Henry Ford" },
    { text: "La acción es la clave fundamental de todo éxito.", author: "Pablo Picasso" },
    { text: "Solo sé que no sé nada.", author: "Sócrates" },
    { text: "La vida no examinada no merece la pena ser vivida.", author: "Sócrates" },
    { text: "El conocimiento es poder.", author: "Francis Bacon" },
    { text: "Pienso, luego existo.", author: "René Descartes" },
    { text: "Lo que no te mata, te hace más fuerte.", author: "Friedrich Nietzsche" },
    { text: "Aquel que tiene un porqué para vivir se puede enfrentar a todos los 'cómos'.", author: "Friedrich Nietzsche" },
    { text: "La simplicidad es la máxima sofisticación.", author: "Leonardo da Vinci" },
    { text: "Aprender sin pensar es tiempo perdido.", author: "Confucio" },
    { text: "El genio es 1% de inspiración y 99% de transpiración.", author: "Thomas Edison" },
    { text: "La innovación distingue a los líderes de los seguidores.", author: "Steve Jobs" },
    { text: "Tu tiempo es limitado, no lo malgastes viviendo la vida de otro.", author: "Steve Jobs" },
    { text: "Mantente hambriento, mantente alocado.", author: "Steve Jobs" },
    { text: "El mayor riesgo es no correr ningún riesgo.", author: "Mark Zuckerberg" },
    { text: "Muévete rápido y rompe cosas.", author: "Mark Zuckerberg" },
    { text: "El éxito es un pésimo maestro. Seduce a la gente inteligente a pensar que no pueden perder.", author: "Bill Gates" },
    { text: "Está bien celebrar el éxito, pero es más importante prestar atención a las lecciones del fracaso.", author: "Bill Gates" },
    { text: "La persistencia es muy importante. No debes rendirte a menos que te veas obligado a rendirte.", author: "Elon Musk" },
    { text: "Cuando algo es lo suficientemente importante, lo haces incluso si las probabilidades no están a tu favor.", author: "Elon Musk" },
    { text: "El primer paso es establecer que algo es posible; entonces la probabilidad ocurrirá.", author: "Elon Musk" },
    { text: "Si quieres algo nuevo, tienes que dejar de hacer algo viejo.", author: "Peter Drucker" },
    { text: "La gestión es hacer las cosas bien; el liderazgo es hacer las cosas correctas.", author: "Peter Drucker" },
    { text: "No puedes gestionar lo que no puedes medir.", author: "Peter Drucker" },
    { text: "El arte de la guerra es someter al enemigo sin luchar.", author: "Sun Tzu" },
    { text: "En medio del caos, también hay oportunidad.", author: "Sun Tzu" },
    { text: "Conócete a ti mismo y conocerás al universo y a los dioses.", author: "Sócrates" },
    { text: "La educación es el arma más poderosa que puedes usar para cambiar el mundo.", author: "Nelson Mandela" },
    { text: "Soy el amo de mi destino, soy el capitán de mi alma.", author: "William Ernest Henley" },
    { text: "El optimismo perpetuo es un multiplicador de fuerzas.", author: "Colin Powell" },
    { text: "El liderazgo es el arte de conseguir que alguien haga algo que tú quieres porque él quiere hacerlo.", author: "Dwight D. Eisenhower" },
    { text: "Los planes son inútiles, pero la planificación lo es todo.", author: "Dwight D. Eisenhower" },
    { text: "No sobreviven las especies más fuertes, ni las más inteligentes, sino las que mejor se adaptan al cambio.", author: "Charles Darwin" },
    { text: "La imaginación es más importante que el conocimiento.", author: "Albert Einstein" },
    { text: "En medio de la dificultad reside la oportunidad.", author: "Albert Einstein" },
    { text: "Locura es hacer lo mismo una y otra vez esperando resultados diferentes.", author: "Albert Einstein" },
    { text: "Todo el mundo es un genio. Pero si juzgas a un pez por su habilidad para trepar árboles, vivirá toda su vida pensando que es un inútil.", author: "Albert Einstein" },
    { text: "No tengo talentos especiales. Solo soy apasionadamente curioso.", author: "Albert Einstein" },
    { text: "La vida es como montar en bicicleta. Para mantener el equilibrio, debes seguir pedaleando.", author: "Albert Einstein" },
    { text: "El tiempo es una ilusión.", author: "Albert Einstein" },
    { text: "Dios no juega a los dados.", author: "Albert Einstein" },
    { text: "El único error real es aquel del que no aprendemos nada.", author: "Henry Ford" },
    { text: "Tanto si piensas que puedes como si piensas que no puedes, tienes razón.", author: "Henry Ford" },
    { text: "El fracaso es simplemente la oportunidad de comenzar de nuevo, esta vez de forma más inteligente.", author: "Henry Ford" },
    { text: "Calidad significa hacer lo correcto cuando nadie está mirando.", author: "Henry Ford" },
    { text: "Si hubiera preguntado a la gente qué querían, me habrían dicho caballos más rápidos.", author: "Henry Ford" },
    { text: "El dinero es como el estiércol: no sirve de nada a menos que se esparza.", author: "Francis Bacon" },
    { text: "La duda es el padre de la invención.", author: "Galileo Galilei" },
    { text: "Y sin embargo, se mueve.", author: "Galileo Galilei" },
    { text: "No se puede enseñar nada a un hombre; solo se le puede ayudar a encontrar la respuesta dentro de sí mismo.", author: "Galileo Galilei" },
    { text: "La medida de lo que somos es lo que hacemos con lo que tenemos.", author: "Vince Lombardi" },
    { text: "La perfección no es alcanzable, pero si perseguimos la perfección podemos conseguir la excelencia.", author: "Vince Lombardi" },
    { text: "Ganar no es todo, es lo único.", author: "Vince Lombardi" },
    { text: "El precio de la grandeza es la responsabilidad.", author: "Winston Churchill" },
    { text: "Nunca, nunca, nunca te rindas.", author: "Winston Churchill" },
    { text: "Un pesimista ve la dificultad en cada oportunidad; un optimista ve la oportunidad en cada dificultad.", author: "Winston Churchill" },
    { text: "La historia será amable conmigo porque tengo la intención de escribirla.", author: "Winston Churchill" },
    { text: "Roma no se construyó en un día.", author: "Proverbio Francés" },
    { text: "Carpe Diem.", author: "Horacio" },
    { text: "Alea jacta est.", author: "Julio César" },
    { text: "Divide y vencerás.", author: "Julio César" },
    { text: "La experiencia es la madre de la sabiduría.", author: "Proverbio" },
    { text: "La paciencia es amarga, pero su fruto es dulce.", author: "Jean-Jacques Rousseau" },
    { text: "La libertad no es nada más que una oportunidad para ser mejor.", author: "Albert Camus" },
    { text: "En lo profundo del invierno, aprendí por fin que dentro de mí hay un verano invencible.", author: "Albert Camus" },
    { text: "Sed el cambio que queréis ver en el mundo.", author: "Mahatma Gandhi" },
    { text: "Vive como si fueras a morir mañana. Aprende como si fueras a vivir para siempre.", author: "Mahatma Gandhi" },
    { text: "Primero te ignoran, luego se ríen de ti, luego te atacan, entonces ganas.", author: "Mahatma Gandhi" },
    { text: "La felicidad es cuando lo que piensas, lo que dices y lo que haces están en armonía.", author: "Mahatma Gandhi" },
    { text: "Ojo por ojo y el mundo acabará ciego.", author: "Mahatma Gandhi" },
    { text: "La fuerza no viene de una capacidad física. Viene de una voluntad indomable.", author: "Mahatma Gandhi" },
    { text: "El futuro depende de lo que hagas hoy.", author: "Mahatma Gandhi" },
    { text: "Un hombre es producto de sus pensamientos. Lo que piensa, se convierte.", author: "Mahatma Gandhi" },
    { text: "No hay camino para la paz, la paz es el camino.", author: "Mahatma Gandhi" },
    { text: "La gloria no consiste en no caer nunca, sino en levantarse cada vez que caes.", author: "Confucio" },
    { text: "Exígete mucho a ti mismo y espera poco de los demás.", author: "Confucio" },
    { text: "Elige un trabajo que te guste y no tendrás que trabajar ni un día de tu vida.", author: "Confucio" },
    { text: "Nuestra mayor gloria no está en no caer nunca, sino en levantarnos cada vez que caemos.", author: "Confucio" },
    { text: "Saber lo que es correcto y no hacerlo es falta de valor.", author: "Confucio" },
    { text: "Quien volviendo a hacer el camino viejo aprende el nuevo, puede considerarse un maestro.", author: "Confucio" },
    { text: "La ignorancia es la noche de la mente, pero una noche sin luna y sin estrellas.", author: "Confucio" },
    { text: "Estudia el pasado si quieres pronosticar el futuro.", author: "Confucio" },
    { text: "El hombre superior es modesto en el hablar, pero abundante en el obrar.", author: "Confucio" }
];

export function getRandomHistoricalQuotes(count = 4) {
    const shuffled = [...historicalQuotes].sort(() => 0.5 - Math.random());
    return shuffled.slice(0, count);
}

export default quotes;
