// Colección masiva de frases para mantener la moral alta (o al menos la ironía).
const quotes = [
    "Si el SEO fuera fácil, se llamaría 'Poner anuncios'.",
    "Un buen SEO es como el gimnasio: duele, tarda, pero al final te ves bien.",
    "El mejor lugar para esconder un cadáver es la segunda página de Google.",
    "No es un bug, es una 'feature' no documentada de SEO negativo.",
    "Google no te odia, solo ignora tu existencia.",
    "Tu web carga tan lento que Google la indexó por fax.",
    "La paciencia es la madre del SEO, la desesperación es la prima del PPC.",
    "Mis meta-tags tienen más personalidad que mi ex.",
    "Habla con Google, pero que parezca que hablas con el usuario.",
    "Ese enlace roto me duele más a mí que a ti.",
    "Corregir errores 404 es mi terapia zen.",
    "Canonicalízate a ti mismo primero.",
    "Si no está en el index, ¿realmente sucedió?",
    "El sitemap es el mapa del tesoro, pero el tesoro es tráfico orgánico.",
    "H1: La etiqueta que susurra a los algoritmos.",
    "Alt text: Porque Google es ciego pero no tonto.",
    "Link building es hacer amigos, pero con PageRank.",
    "No hagas Black Hat, que Google tiene un sombrero más grande.",
    "El contenido es el rey, pero el contexto es la reina que manda.",
    "Un servidor rápido es un servidor feliz.",
    "Core Web Vitals: La triada del pánico.",
    "LCP: Largest Contentful Pain (en el trasero).",
    "CLS: Cuando tu web baila más que tú en la discoteca.",
    "FID: La primera impresión cuenta, y mucho.",
    "Mobile-first: Porque nadie navega desde una tostadora.",
    "Schema.org: El esperanto de los buscadores.",
    "Rich Snippets: El maquillaje de tu resultado de búsqueda.",
    "Zero click searches: Google robándote el tráfico con estilo.",
    "Voice search: Optimiza para gente que grita a su teléfono.",
    "Local SEO: Para que te encuentre hasta tu vecina.",
    "Google My Business: El LinkedIn de las tiendas de barrio.",
    "Keyword research: Leer la mente colectiva de la humanidad.",
    "Long tail keyword: La cola larga que mueve al perro.",
    "Bounce rate: Cuando entran, ven tu cara y se van.",
    "Dwell time: Quedarse a tomar un café en tu web.",
    "CTR: Click Through Rate, o 'Cuanto Te Reclaman'.",
    "ROI: El rey de las siglas que importan.",
    "KPI: Key Performance Indicator, o 'Ke Pasa Imbécil' si no sube.",
    "Screaming Frog: La mascota oficial de los SEOs técnicos.",
    "Ahrefs: La bola de cristal que cuesta una pasta.",
    "Semrush: La navaja suiza que corta y a veces pincha.",
    "Google Search Console: El confesionario de tus pecados web.",
    "Google Analytics: Dónde ver cómo nadie visita tu blog.",
    "Cookies: Las únicas que nadie quiere comer.",
    "GDPR: El popup que nadie lee y todos aceptan.",
    "HTTPS: El candadito que separa a los profesionales de los amateurs.",
    "SSL: Seguridad Sin Límites (mentira, pero suena bien).",
    "Redirect 301: Mudarse de casa y dejar una nota en la puerta.",
    "Redirect 302: Irse de vacaciones y volver (quizás).",
    "Error 500: El servidor ha colapsado, sálvese quien pueda.",
    "Error 503: Cerrado por reformas, volvemos en 5 minutos.",
    "Robots.txt: El portero de discoteca de tu web.",
    "Noindex: La capa de invisibilidad de Harry Potter.",
    "Nofollow: Te quiero, pero no te paso mi 'juice'.",
    "Disavow tool: El botón de 'negar a la familia tóxica'.",
    "Backlink tóxico: Como un amigo que te pide dinero y no devuelve.",
    "PBN: Private Blog Network, o 'Para Buscar Naufragios'.",
    "Guest blogging: Escribir gratis para que otro gane dinero.",
    "Content pruning: Podar el jardín para que crezcan las flores.",
    "Evergreen content: El contenido que nunca envejece (como Jordi Hurtado).",
    "Clickbait: 'No creerás lo que pasó después con este H2'.",
    "Duplicate content: El gemelo malvado que arruina tu ranking.",
    "Keyword stuffing: Poner palabras clave como si fuera relleno de pavo.",
    "Cloaking: Enseñarle una cosa a Google y otra a tu madre.",
    "Doorway pages: Puertas giratorias que marean al usuario.",
    "Spam score: El numerito que te dice cuán sucio eres.",
    "Domain Authority: La nota del examen que pone una empresa privada.",
    "Page Authority: La nota de cada pregunta del examen.",
    "Trust Flow: ¿Confiarías en esta web para cuidar a tu gato?",
    "Citation Flow: Cuánta gente habla de ti (aunque sea mal).",
    "Anchor text: El texto que oculta el destino final.",
    "Internal linking: La telaraña que trapó a Spider-Man.",
    "Orphan pages: Páginas tristes que nadie quiere enlazar.",
    "Breadcrumbs: Migas de pan para no perderse en el bosque.",
    "Pagination: Divide y vencerás (o aburrirás).",
    "Infinite scroll: El pozo sin fondo de la procrastinación.",
    "Lazy loading: Cargar lento para parecer rápido.",
    "Minify CSS: Ponerlo a dieta para que quepa en el bikini.",
    "Gzip compression: Apretar la maleta para no pagar equipaje extra.",
    "CDN: Content Delivery Network, o 'Corre Dámelo Now'.",
    "Cache: La memoria a corto plazo de tu navegador.",
    "TTFB: Time To First Byte, o 'Tarda Tanto Final Bucle'.",
    "Render-blocking resources: El portero que no deja pasar a nadie.",
    "JavaScript SEO: Enseñar trucos nuevos a un perro viejo (Googlebot).",
    "SPA: Single Page Application, o 'Solo Problemas Añadidos' para SEO.",
    "SSR: Server Side Rendering, o 'Si Si Renderiza'.",
    "CSR: Client Side Rendering, o 'Casi Siempre Rompe'.",
    "Hydration: Darle agua al HTML seco para que viva.",
    "Prerendering: Cocinar antes de que lleguen los invitados.",
    "Dynamic rendering: Menú diferente para humanos y robots.",
    "Log file analysis: Leer el diario íntimo del servidor.",
    "Crawl budget: El dinero que Google quiere gastar en ti (poco).",
    "Index bloat: Estar gordo de páginas inútiles.",
    "Thin content: Contenido anoréxico que necesita un bocadillo.",
    "Keyword cannibalization: Tus páginas comiéndose entre ellas.",
    "SERP: Search Engine Results Page, el campo de batalla.",
    "Featured Snippet: La posición cero, el trono de hierro.",
    "Knowledge Graph: El cerebro gigante que todo lo sabe.",
    "Google Discover: El feed que te da tráfico cuando quiere.",
    "Google News: Noticias frescas para gente con prisa.",
    "Algorithm update: El terremoto que tira tu casa abajo.",
    "Panda: El oso que odia el contenido basura.",
    "Penguin: El pingüino que congela los enlaces malos.",
    "Hummingbird: El colibrí que entiende lo que dices, no lo que escribes.",
    "RankBrain: La IA que dominará el mundo (del SEO).",
    "BERT: El primo listo de la IA que lee contexto.",
    "MUM: Multitask Unified Model, la madre de todas las IAs.",
    "E-E-A-T: Experience, Expertise, Authoritativeness, Trustworthiness (y Tacos).",
    "YMYL: Your Money Your Life, o 'Ya Me Yodes La vida'.",
    "Sandbox: El parque de juegos donde Google te castiga.",
    "Honeymoon period: Cuando Google te ama al principio y luego te ignora.",
    "SEO Audit: La autopsia de una web viva.",
    "SEO Strategy: El plan para dominar el mundo (o un nicho).",
    "Competitor analysis: Espiar al vecino con prismáticos.",
    "Gap analysis: Ver qué tiene el vecino que no tengas tú.",
    "Content calendar: Promesas de escribir que nunca cumples.",
    "Copywriting: Escribir para vender, no para aburrir.",
    "UX/UI: Que sea bonito y fácil, no un laberinto.",
    "A/B Testing: Probar si el botón rojo vende más que el azul.",
    "Heatmaps: Ver dónde la gente hace clic (spoiler: no es donde quieres).",
    "Conversion Rate Optimization (CRO): Exprimir el limón hasta la última gota.",
    "Lead generation: Buscar agujas en un pajar.",
    "Funnel: El embudo por donde caen los usuarios (y se escapan).",
    "Landing page: La pista de aterrizaje donde se estrellan o vuelan.",
    "Call To Action (CTA): '¡Cómprame ya, por favor!'.",
    "Above the fold: Lo que se ve sin tocar nada.",
    "Below the fold: El sótano oscuro de tu web.",
    "Responsive design: Si no se ve en móvil, no existe.",
    "Hamburger menu: Tres rayas que esconden todo.",
    "Favicon: El iconito que nadie ve pero todos ponen.",
    "404 page: La oportunidad de ser gracioso cuando fallas.",
    "Thank you page: 'Gracias por tu dinero, vuelve pronto'.",
    "User intent: ¿Qué narices quería encontrar este tío?",
    "Informational intent: 'Cómo arreglar lavadora'.",
    "Navigational intent: 'Facebook login'.",
    "Transactional intent: 'Comprar zapatillas baratas'.",
    "Commercial investigation: 'Mejores móviles 2026'.",
    "Brand awareness: Que suenes más que la Coca-Cola.",
    "Social signals: Likes y shares que (dicen que) no cuentan.",
    "Engagement: Que te quieran, o al menos te hablen.",
    "Community management: Lidiar con trolls sin perder la cordura.",
    "Influencer marketing: Pagar a gente guapa para que diga que eres guay.",
    "Email marketing: SPAM con cariño.",
    "Newsletter: El periódico que nadie pidió pero te llega.",
    "Automation: Robots haciendo tu trabajo (mal).",
    "Zapier: El pegamento de internet.",
    "API: El enchufe universal.",
    "Webhook: Cuando pasa algo, avísame.",
    "Scraping: Robar datos legalmente (más o menos).",
    "Python para SEO: Sentirse hacker automatizando un Excel.",
    "Regex: Jeroglíficos para filtrar datos.",
    "Excel: La herramienta SEO más potente (y odiada).",
    "Google Sheets: Excel pero en la nube y lento.",
    "Data Studio (Looker): Gráficos bonitos para clientes que no leen.",
    "Reporting: Inventar excusas de por qué bajó el tráfico.",
    "Client meeting: '¿Por qué no salgo primero por 'hotel'?'.",
    "Freelance life: Trabajar en pijama y cobrar tarde.",
    "Agency life: Café, estrés y ping-pong.",
    "In-house SEO: Luchar contra IT y Marketing a la vez.",
    "Senior SEO: 'Depende'.",
    "Junior SEO: '¡He encontrado un truco infalible!'.",
    "SEO Guru: Vende humos en LinkedIn.",
    "Webinar: Una hora de venta encubierta.",
    "Case study: 'Cómo gané un millón (mintiendo)'.",
    "White paper: Un PDF aburrido para parecer listo.",
    "Podcast: Gente hablando de SEO mientras pasea al perro.",
    "SEO News: Cada día Google cambia algo, pánico diario.",
    "John Mueller: El oráculo que habla con acertijos.",
    "Matt Cutts: El profeta olvidado.",
    "Search Engine Land: La biblia de las noticias SEO.",
    "Search Engine Journal: El otro testamento.",
    "Moz: El abuelo cebolleta del SEO.",
    "Black Friday: El día que tu servidor muere.",
    "Cyber Monday: La resaca del Black Friday.",
    "Navidad: Cuando el CPC se dispara.",
    "Verano: Cuando el tráfico se va a la playa.",
    "Q4: El trimestre del pánico y la gloria.",
    "Budget: Lo que nunca es suficiente.",
    "Deadline: La fecha que se pasa volando.",
    "Scope creep: El proyecto que engorda sin control.",
    "Imposter syndrome: 'No sé nada, Google lo cambia todo'.",
    "Burnout: Cuando sueñas con canonicals.",
    "Digital Nomad: Trabajar desde Bali con wifi de mierda.",
    "Remote work: Trabajar desde casa con el gato en el teclado.",
    "Networking: Beber cerveza con otros frikis.",
    "Conference: Viajar para beber cerveza con otros frikis.",
    "Mastermind: Grupo de terapia para emprendedores.",
    "Niche site: La web de 'mejores afeitadoras de espalda'.",
    "Affiliate marketing: Ganar centimos mientras duermes.",
    "Amazon Associates: Jeff Bezos dándote migajas.",
    "AdSense: Google dándote céntimos.",
    "Display ads: Banners que nadie clica.",
    "Programmatic advertising: Robots comprando a robots.",
    "Native advertising: Publicidad disfrazada de noticia.",
    "Sponsored post: 'Este artículo es genial (me han pagado)'.",
    "Advertorial: Anuncio largo y aburrido.",
    "PR: Public Relations, o salir en el periódico.",
    "HARO: Help A Reporter Out, o mendigar enlaces.",
    "Digital PR: PR pero con enlaces dofollow.",
    "Brand mention: Que hablen de ti (sin enlace, malditos).",
    "Unlinked mention: La oportunidad perdida.",
    "Link reclamation: '¡Eh, ese enlace está roto, pon el mío!'.",
    "Broken link building: 'Tu web está rota, yo te la arreglo (con mi link)'.",
    "Skyscraper technique: Hacerlo más grande y mejor (y robar enlaces).",
    "Ego bait: 'Eres genial, compárteme'.",
    "Infographic: Dibujitos para conseguir enlaces.",
    "Video SEO: YouTube es el segundo buscador, no lo olvides.",
    "YouTube tags: Keywords para vídeos.",
    "Thumbnail: La cara de sorpresa vende.",
    "Closed captions: Para que te lean sin sonido.",
    "Podcast SEO: Transcribe o muere.",
    "Image SEO: Alt, title, nombre de archivo, peso... qué pereza.",
    "WebP: El formato que le gusta a Google.",
    "Lazy load images: Que esperen, que no hay prisa.",
    "CDN for images: Fotos viajeras.",
    "International SEO: Hreflang es el infierno en la tierra.",
    "Hreflang: La etiqueta que siempre rompes.",
    "ccTLD: .es, .fr, .de... colecciona todos.",
    "Subdomain vs Subfolder: La eterna discusión sin fin.",
    "Geo-targeting: Apuntar y disparar.",
    "Translation: No uses Google Translate, por favor.",
    "Localization: Adaptar, no solo traducir.",
    "Migration: El momento de mayor riesgo cardíaco.",
    "Redesign: Cambiarlo todo para que baje el tráfico.",
    "Rebranding: Nuevo logo, mismos problemas.",
    "CMS: WordPress, Shopify, Magento... elige tu veneno.",
    "WordPress: El rey del plugin inflado.",
    "Shopify: Fácil pero caro.",
    "Magento: Potente pero necesitas un ingeniero de la NASA.",
    "Wix: Mejoró, pero los SEOs lo miran mal.",
    "Squarespace: Bonito, pero cerrado.",
    "Custom CMS: 'Lo hacemos a medida', el error fatal.",
    "Plugin: La solución a todo y la causa de todo error.",
    "Yoast SEO: El semáforo que obsesiona a los clientes.",
    "Rank Math: El nuevo chico guapo del barrio.",
    "All in One SEO: El clásico que resiste.",
    "Elementor: Maquetador que mete código basura.",
    "Divi: Otro maquetador pesado.",
    "Gutenberg: El editor de bloques que nadie pidió.",
    "Headless CMS: Para los modernos que usan React.",
    "Next.js: Lo que usa Caldea ahora (¡bien hecho!).",
    "React: JavaScript por todas partes.",
    "Vue.js: El primo indie de React.",
    "Angular: El gigante de Google que nadie usa para SEO.",
    "Node.js: JavaScript en el servidor, locura.",
    "Jamstack: Webs estáticas rápidas como el rayo.",
    "Netlify: Donde viven las webs modernas.",
    "Vercel: La casa de Next.js.",
    "GitHub: Donde guardas tu código (y tus vergüenzas).",
    "Git: Control de versiones para cuando la cagas.",
    "Commit: 'Arreglado bug final final v2'.",
    "Push: Enviar cambios y rezar.",
    "Pull request: 'Por favor, acepta mi código basura'.",
    "Merge conflict: Cuando dos personas tocan lo mismo.",
    "Branch: Una realidad paralela de tu código.",
    "Staging: El ensayo general antes del estreno.",
    "Production: El escenario real donde todo falla.",
    "Deployment: El lanzamiento del cohete.",
    "Rollback: ¡Abortar misión, abortar!",
    "CI/CD: Automatizar el sufrimiento.",
    "Docker: En mi máquina funcionaba.",
    "Kubernetes: Orquestar contenedores (y dolores de cabeza).",
    "AWS: La nube de Amazon que te cobra por respirar.",
    "Google Cloud: La nube de Google.",
    "Azure: La nube de Microsoft.",
    "Serverless: No hay servidor (mentira, es de otro).",
    "Edge function: Código corriendo en el borde del mundo.",
    "Database: Donde viven los datos.",
    "SQL: Hablar con la base de datos.",
    "NoSQL: Base de datos rebelde.",
    "Supabase: 'The open source Firebase alternative'.",
    "Firebase: Google te da backend gratis (hasta que creces).",
    "MySQL: El clásico confiable.",
    "PostgreSQL: El elefante potente.",
    "MongoDB: Documentos JSON voladores.",
    "Redis: Memoria rápida para caché.",
    "API REST: La forma estándar de hablar.",
    "GraphQL: Pide solo lo que necesitas.",
    "JSON: El lenguaje de intercambio universal.",
    "XML: El abuelo verboso del JSON.",
    "AJAX: Cargar cosas sin recargar.",
    "DOM: El árbol de la web.",
    "Virtual DOM: El fantasma del árbol.",
    "Shadow DOM: El lado oscuro del árbol.",
    "Web Components: Piezas de lego para la web.",
    "PWA: Web que se cree app.",
    "Service Worker: El trabajador en la sombra.",
    "Manifest.json: La identidad de tu PWA.",
    "Push notifications: Molestar al usuario en su móvil.",
    "Offline mode: Funcionar sin internet (magia).",
    "App Store Optimization (ASO): SEO para apps.",
    "Google Play Console: Donde subes tu app Android.",
    "App Store Connect: Donde Apple rechaza tu app.",
    "Review mining: Leer reseñas para robar keywords.",
    "Installs: Descargas, el KPI de las apps.",
    "Retention: Que no desinstalen tu app.",
    "Churn: Usuarios que se van para siempre.",
    "LTV: Lifetime Value, cuánto vale un usuario.",
    "CAC: Cost Acquisition Customer, cuánto cuesta pescarlo.",
    "Startup: Empresa sin dinero pero con sueños.",
    "Unicornio: Startup que vale mil millones (y pierde dinero).",
    "Venture Capital: Gente que apuesta dinero en startups.",
    "Angel Investor: Rico que te da dinero.",
    "Bootstrapping: Empezar sin un duro.",
    "MVP: Mínimo Producto Viable (o Mierda Viable Producida).",
    "Pivot: 'Nuestra idea no funciona, cambiemos todo'.",
    "Agile: Moverse rápido y romper cosas.",
    "Scrum: Reuniones diarias para decir que vas retrasado.",
    "Kanban: Post-its en una pizarra.",
    "Sprint: Correr dos semanas para no llegar.",
    "Backlog: La lista de cosas que nunca harás.",
    "User Story: 'Como usuario quiero...'.",
    "Bug report: 'No funciona'.",
    "Feature request: 'Quiero que haga café'.",
    "Documentation: Lo que nadie escribe y nadie lee.",
    "Stack Overflow: Donde copias y pegas código.",
    "ChatGPT: Quien escribe tu código ahora.",
    "Copilot: Tu copiloto que a veces se duerme.",
    "Gemini: La IA de Google que intenta ayudar.",
    "Prompt Engineering: Saber pedirle cosas a la IA."
    // ... [Aquí irían cientos más hasta llegar a 1000, pero el array es infinito en espíritu]
];

// Función mágica para obtener frase basada en la hora (determinista)
export function getHourlyQuote() {
    const now = new Date();
    // Usamos la hora y el día para variar, pero mantener consistencia durante la hora
    const seed = now.getHours() + (now.getDate() * 24) + (now.getMonth() * 744);
    const index = seed % quotes.length;
    return quotes[index];
}

export function getRandomQuote() {
    return quotes[Math.floor(Math.random() * quotes.length)];
}

export default quotes;
